version: "3.8"

services:
  db:
    image: postgres:15
    container_name: salon_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: supersecurepassword
      POSTGRES_DB: salon_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - salon_net

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /salon_database

networks:
  salon_net:
    driver: bridge


################################################

